spring:
  application:
    name: redseeker-backend
  datasource:
    url: jdbc:mysql://localhost:3306/redseeker
    username: root
    password: password

server:
  port: 8080

amap:
  key: "bfa236c5b4ff2d954936faa864c1a490"
  base-url: "https://restapi.amap.com"
