spring:
  application:
    name: redseeker-backend
  datasource:
    url: jdbc:mysql://localhost:3306/redseeker
    username: root
    password: password

server:
  port: 8080

zhipu:
  api:
    key: "dc429f40fc2d4c42af23eed404a1ba2b.d4Bq0fTcEyIYrEMc" # 请替换为您的API Key

